---
- name: Install applications using Winget
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Run a Powershell script on a Windows host
      playbook-ansible-winget-ps:
        state: present
        appID: git.git
