---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install 7zip
      playbook-ansible-winget-ps:
        state: present
        appID: 7zip.7zip
        vars:
          ansible_command_timeout: 30

    - name: Install 7zip
      playbook-ansible-winget-ps:
        state: present
        appID: Git.Git

    - name: Install 7zip
      playbook-ansible-winget-ps:
        state: present
        appID: Notepad++.Notepad++