---
- name: Install applications using Winget
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - include_tasks: winget.yml

    - name: Ensure Firefox is installed
      playbook-ansible-winget-ps:
        package: Mozilla.Firefox
        action: install

    - name: Ensure OneDrive is removed
      playbook-ansible-winget-ps:
        package: Microsoft.OneDrive
        action: uninstall

    - name: Ensure ThunderBird is upgraded to the latest version
      playbook-ansible-winget-ps:
        package: Mozilla.ThunderBird
        action: install

