---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false
  become: true

  tasks:
  
    - name: Install 7zip
      ansible-winget:
        state: present
        appID: 7zip.7zip
      async: 360
      poll: 15

    - name: Install Git
      ansible-winget:
        state: present
        appID: Git.Git
      async: 360
      poll: 15

    - name: Install Mozilla Thunderbird
      ansible-winget:
        state: present
        appID: Mozilla.Thunderbird
      async: 360
      poll: 15
