---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install 7zip
      playbook-ansible-winget-ps:
        state: present
        appID: 7zip.7zip
      async: 360
      poll: 60

