---
- name: Manage packages with Winget
  hosts: all
  tasks:
    - name: Install package
      win_shell: powershell.exe -File C:\path\to\winget_module.ps1 -action install -package "{{ package_name }}"
      when: action == "install"

    - name: Uninstall package
      win_shell: powershell.exe -File C:\path\to\winget_module.ps1 -action uninstall -package "{{ package_name }}"
      when: action == "uninstall"