---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false


  tasks:
  
    - name: Install 7zip
      ansible-winget:
        state: absent
        appID: 7zip.7zip

    - name: Uninstall Git
      ansible-winget:
        state: present
        appID: Git.Git

    - name: Update Mozilla Thunderbird
      ansible-winget:
        state: updated
        appID: Mozilla.Thunderbird
