---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false

  tasks:
  
    - name: Install Google.Chrome
      ansible-winget:
        appID: Google.Chrome
        state: present
        version: 123.0.6312.106

