---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false

  tasks:
  
    - name: Uninstall VLC media player
      ansible-winget:
        appID: VideoLAN.VLC
        state: absent
        version: 123.0.6312.106

