---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false

  tasks:
  
    - name: Install Git
      ansible-winget:
        appID: Git.Git
        state: present

    - name: Uninstall 7zip
      ansible-winget:
        appID: 7zip.7zip
        state: absent

    - name: Uninstall VLC
      ansible-winget:
        appID: VideoLAN.VLC
        state: absent

    - name: Install Mozilla Firefox
      ansible-winget:
        appID: Mozilla.Firefox.VLC
        state: present