---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false

  tasks:
  
    - name: Install VLC media player
      ansible-winget:
        appID: VideoLAN.VLC
        state: present
        architecture: x64
        scope: machine
        version: 3.0.19

    - name: Update VLC media player
      ansible-winget:
        appID: VideoLAN.VLC
        state: updated
        architecture: x64
        scope: machine

    - name: Uninstall VLC media player
      ansible-winget:
        appID: VideoLAN.VLC
        state: absent
        scope: machine
        version: 3.0.20
        