---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false


  tasks:
  
    - name: Update Microsoft PowerToys
      test:
        state: updated
        appID: Microsoft.PowerToys
        scope: user
        version: 0.81.0
