---
- name: Manage applications using Winget
  hosts: all
  gather_facts: false

  tasks:
  
    - name: Uninstall VLC media player
      ansible-winget:
        appID: VideoLAN.VLC
        state: absent

    - name: Uninstall 7zip.7zip
      ansible-winget:
        appID: 7zip.7zip
        state: absent

    - name: Uninstall Mozilla.Thunderbird
      ansible-winget:
        appID: Mozilla.Thunderbird
        state: absent
